/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SMK TELKOM
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bar1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        bar2 = new javax.swing.JTextField();
        bar3 = new javax.swing.JTextField();
        bar4 = new javax.swing.JTextField();
        dis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Hps = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 100, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Harga Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 100, 30);
        getContentPane().add(bar1);
        bar1.setBounds(120, 50, 160, 30);

        jPanel1.setBackground(new java.awt.Color(102, 204, 0));
        jPanel1.setLayout(null);
        jPanel1.add(bar2);
        bar2.setBounds(120, 80, 160, 30);
        jPanel1.add(bar3);
        bar3.setBounds(120, 110, 160, 30);

        bar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bar4ActionPerformed(evt);
            }
        });
        jPanel1.add(bar4);
        bar4.setBounds(120, 140, 160, 30);
        jPanel1.add(dis);
        dis.setBounds(120, 170, 160, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Harga Barang 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 90, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Harga Barang 3");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 110, 100, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Harga Barang 4");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 150, 90, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Diskon");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 180, 70, 17);

        OK.setText("Proses");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        jPanel1.add(OK);
        OK.setBounds(50, 220, 90, 23);

        Hps.setText("Hapus");
        Hps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HpsActionPerformed(evt);
            }
        });
        jPanel1.add(Hps);
        Hps.setBounds(150, 220, 90, 23);

        Exit.setText("Keluar");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit);
        Exit.setBounds(250, 220, 90, 23);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 250, 240, 130);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 430);

        setBounds(0, 0, 372, 445);
    }// </editor-fold>//GEN-END:initComponents

    private void bar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bar4ActionPerformed

    private void HpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HpsActionPerformed
        // TODO add your handling code here:
        TA.setText("");
        bar1.setText("");
        bar2.setText("");
        bar3.setText("");
        bar4.setText("");
        dis.setText("");
    }//GEN-LAST:event_HpsActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        int br1 = Integer.parseInt(bar1.getText());
        int br2 = Integer.parseInt(bar2.getText());
        int br3 = Integer.parseInt(bar3.getText());
        int br4 = Integer.parseInt(bar4.getText());
        int diskon = Integer.parseInt(dis.getText());
        int total1;
        int total;
        int harga;
        
        harga = br1+br2+br3+br4;
        if (diskon == 0){
            total = harga;
        }
        else{
            total1 = harga*diskon/100;
            total= harga - total1;
        }
        TA.setText("Harga Barang 1: "+br1+"\nHarga Barang 2: "+br2+"\nHarga Barang 3: "+br3+
                "\nHarga Barang 4: "+br4+"\nDiskon: "+diskon+"\nTotal Harga: "+harga+
                "\nTotal Bayar: "+total);
    }//GEN-LAST:event_OKActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Hps;
    private javax.swing.JButton OK;
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField bar1;
    private javax.swing.JTextField bar2;
    private javax.swing.JTextField bar3;
    private javax.swing.JTextField bar4;
    private javax.swing.JTextField dis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
